# Generated by Django 4.2.23 on 2025-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='refreshtokenstore',
            index=models.Index(fields=['expires_at'], name='core_refres_expires_502ac9_idx'),
        ),
        migrations.AddConstraint(
            model_name='refreshtokenstore',
            constraint=models.UniqueConstraint(fields=('user',), name='uq_refresh_one_per_user'),
        ),
    ]
