# Generated by Django 4.2.23 on 2025-08-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='summary_text',
        ),
        migrations.AddField(
            model_name='document',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='summaries/'),
        ),
    ]
